version: '3.2'
services:
  db:
    image: "mysql:5.7.22"
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - type: bind
        source: ./docker/db/init.sql
        target: /docker-entrypoint-initdb.d/init.sql
      - type: bind
        source: /tmp/docker/tmpdata
        target: /tmp/tmpdata
